"""Generate packages/core/src/casefold.generated.ts from Python's str.casefold().

livesaver compares file and plug-in names case-insensitively with Unicode full case folding (C+F,
what Python's str.casefold() does: the ligature "ﬁ" folds to "fi"). JavaScript has no casefold, so the
mapping is shipped as a table. Only code points
whose casefold differs from toLowerCase() in JS terms are relevant, but we ship every non-identity
mapping to keep the implementation trivially correct. Re-run when Python's Unicode version changes.

Usage: python3 scripts/gen-casefold.py
"""
import json
import os
import sys
import unicodedata

rows = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    folded = ch.casefold()
    if folded != ch:
        rows.append((cp, folded))

# Compact encoding: "cp:hex hex …" entries joined by ";", hex without prefix.
encoded = ";".join(
    f"{cp:x}:{' '.join(f'{ord(c):x}' for c in folded)}" for cp, folded in rows
)
out = os.path.join(os.path.dirname(__file__), "..", "packages", "core", "src", "casefold.generated.ts")
with open(out, "w", encoding="utf-8") as fh:
    fh.write("// Generated by scripts/gen-casefold.py from Python "
             f"{sys.version.split()[0]} (Unicode {unicodedata.unidata_version}). Do not edit.\n")
    fh.write(f"export const UNICODE_VERSION = {json.dumps(unicodedata.unidata_version)}\n")
    fh.write(f"export const CASEFOLD_TABLE = {json.dumps(encoded)}\n")
print(f"{len(rows)} mappings, {len(encoded)} chars -> {os.path.normpath(out)}")
